### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by marz869** [topazape/LSTM_Chem#6]
Hi 
Thanks for your great job.
At the end of epoch 2 before saving model and last iteration I got this error:
`Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\Radical\Anaconda3\envs\myenv\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Radical\Anaconda3\envs\myenv\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Radical\Anaconda3\envs\myenv\lib\site-packages\tensorflow_core\python\keras\utils\data_utils.py", line 748, in _run
    with closing(self.executor_fn(_SHARED_SEQUENCES)) as executor:
  File "C:\Users\Radical\Anaconda3\envs\myenv\lib\site-packages\tensorflow_core\python\keras\utils\data_utils.py", line 727, in pool_fn
    initargs=(seqs, None, get_worker_id_queue()))
  File "C:\Users\Radical\Anaconda3\envs\myenv\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\Radical\Anaconda3\envs\myenv\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\Users\Radical\Anaconda3\envs\myenv\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\Users\Radical\Anaconda3\envs\myenv\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\Radical\Anaconda3\envs\myenv\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Radical\Anaconda3\envs\myenv\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Radical\Anaconda3\envs\myenv\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
RuntimeError: dictionary changed size during iteration

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Radical\Anaconda3\envs\myenv\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Radical\Anaconda3\envs\myenv\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input`

would you explain why it is happening or fixed it.. thank you.

**Comment by topazape** [comment]
Maybe that error is due to something in tensorflow 2.0.0, but I can't say for sure. I am currently rewriting the code for tensorflow 2.1.0, so please submit the issue if you are experiencing similar errors in newer versions.
Thanks,

**Comment by topazape** [comment]
@marz869 Please try new version.
